name: freshOk
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  get_it: ^4.0.2
  flutter_bloc: ^6.0.1
  equatable: ^1.2.0
  dartz: ^0.9.1
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  flutter_secure_storage: ^3.3.3
  # for the otp input field
  pin_code_fields: ^4.0.0
  #for dotted border in recepie create section
  dotted_border: ^1.0.6
  firebase_messaging: ^6.0.16
  flutter_local_notifications: ^1.4.4+2
  youtube_player_flutter: ^7.0.0+7
  shimmer: ^1.1.1
  flutter_share_me: ^0.9.1
  firebase_dynamic_links: ^0.5.3
  socket_io_client: ^0.9.11
  flutter_svg: ^0.17.4
  razorpay_flutter: 1.1.0
  url_launcher: ^5.5.0
  image_picker: ^0.6.7+4
  image_cropper: ^1.3.0
  flutter_image_compress: ^0.7.0
  path_provider: ^1.6.11
  webview_flutter: ^0.3.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/test/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
